asset_id: [asset_id, Asset ID, Asset Id, Asset Record ID, Record ID]
site_id: [site_id, Site ID, Site Id, Site Record ID]
asset_name: [asset_name, Name of Asset, Asset Name]
site_name: [site_name, Name of Site, Site Name]
site_name_lookup: [Name (from Site)]
municipality: [municipality, Municipality, Town, City]
subregion: [subregion, Subregion, Subregion (from Site)]
latitude: [latitude, Latitude, Lat]
longitude: [longitude, Longitude, Lon, Lng, Long]
coordinates_raw: [coordinates_raw, Location, Coordinates, coordinates, GPS Location]
attributes_raw: [attributes_raw, Attributes, Attribute, recorded_attributes]
activities_raw: [activities_raw, Activities, Activity, activities]
field_description: [field_description, Description, Asset Description]
accessibility_description: [accessibility_description, Accessibility Description]
field_validated: [field_validated, 'Data Collector Finished?', 'Field Visit Complete?', Field Validated, Data Collector Finished, Field Visit Complete]
staff_reviewed: [staff_reviewed, 'Staff Reviewed?', Staff Reviewed]
seo_description: [SEO Description]
street: [Street, street, Address]
zip_code: [Zip Code, Postal Code, zip_code]
rental_equipment_raw: ['Rental Equipment Available?']
seasonal_raw: [Seasonal, Seasonal ]
field_visitor_notes: [Note for field visitors, Field Notes]
photos_done_raw: ['Photos done?', Photos Done]
