"""Portable XlsxWriter exports, typed data, native charts and round-trip checks."""
from __future__ import annotations

from pathlib import Path
import json
import math
import re

import numpy as np
import pandas as pd
import xlsxwriter
from openpyxl import load_workbook

from .analysis import PROFILES


def cell_value(value):
    if isinstance(value, (list, tuple, dict, set)):
        if isinstance(value, set):
            value = sorted(value)
        return json.dumps(value, ensure_ascii=False, default=str)
    if value is None or (isinstance(value, (float, np.floating)) and not math.isfinite(value)):
        return None
    if isinstance(value, (np.integer,)):
        return int(value)
    if isinstance(value, (np.bool_,)):
        return bool(value)
    if isinstance(value, (np.floating,)):
        return float(value)
    if value is pd.NA:
        return None
    return value


def csv_frame(frame):
    result = frame.copy()
    for col in result.columns:
        result[col] = result[col].map(cell_value)
    return result


class Book:
    """Consistent, bounded spreadsheet formatting without modifying data values."""
    def __init__(self, path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.workbook = xlsxwriter.Workbook(self.path, {"strings_to_formulas": False, "strings_to_urls": False})
        self.workbook.set_properties({"title": "MAPC recreation inventory", "author": "MAPC recreation analysis project",
                                      "comments": "Generated from immutable inputs by the versioned Python pipeline."})
        self.formats = {}
        common = {"font_name": "Arial", "font_size": 10, "valign": "vcenter", "font_color": "#253748"}
        for name, props in {
            "text": {}, "int": {"num_format": "#,##0"}, "float": {"num_format": "0.00"},
            "percent": {"num_format": "0.0%"}, "wrap": {"text_wrap": True, "valign": "top"},
            "header": {"bold": True, "bg_color": "#244866", "font_color": "#FFFFFF", "text_wrap": True, "align": "center"},
            "title": {"font_size": 16, "bold": True, "font_color": "#17324D"},
            "section": {"bold": True, "font_size": 11, "bottom": 1, "bottom_color": "#A9B8C6"},
            "note": {"font_size": 10, "italic": True, "font_color": "#566575"},
            "warning": {"font_color": "#8A5200", "bg_color": "#FFF1D1"},
        }.items():
            self.formats[name] = self.workbook.add_format({**common, **props})
        self.table_number = 0
        self.specs = []
        self.column_widths = {}

    def sheet(self, name, title=None):
        ws = self.workbook.add_worksheet(name)
        ws.hide_gridlines(2)
        ws.set_default_row(18)
        ws.set_zoom(90)
        ws.set_landscape(); ws.fit_to_pages(1, 0)
        ws.set_margins(.3, .3, .4, .4)
        ws.set_header("&LMAPC recreation inventory&R&A")
        ws.set_footer("&LGenerated by the reproducible analysis pipeline&RPage &P of &N")
        if title:
            ws.write(1, 0, title, self.formats["title"])
            ws.set_row(1, 27)
        return ws

    def table(self, ws, frame, row=0, title=None, note=None, data_sheet=False):
        if title:
            ws.write(row, 0, title, self.formats["section"])
            row += 1
        if note:
            # One readable note line per cell across a large width; no data merges.
            import textwrap
            for line in textwrap.wrap(note, 128):
                ws.write(row, 0, line, self.formats["note"])
                row += 1
        start = row
        if len(frame.columns) == 0:
            ws.write(row, 0, "No records available", self.formats["note"])
            return row + 3
        for i, col in enumerate(frame.columns):
            vals = frame[col].map(cell_value).tolist()
            strings = [str(v) for v in vals if v is not None]
            width = min(46, max(15, len(str(col)) * .80 + 2, min(max((len(v) for v in strings), default=0), 34) + 2))
            if any(k in col for k in ["description", "derivation", "finding", "limitation", "notes", "evidence", "allowed_values", "missing_value_rule", "verification_meaning"]):
                width = 58
            if col.endswith("_list") or col.endswith("_json"):
                width = 45
            numeric = pd.api.types.is_numeric_dtype(frame[col]) and not pd.api.types.is_bool_dtype(frame[col])
            fmt = self.formats["percent"] if "share" in col.split("_") else self.formats["float"] if any(s in col for s in ["mean", "median", "q1", "q3", "distance", "rho", "latitude", "longitude"]) else self.formats["int"] if numeric else self.formats["text"]
            width = max(width, self.column_widths.get((ws.name, i), 0))
            self.column_widths[(ws.name, i)] = width
            ws.set_column(i, i, width, fmt)
            ws.write(start, i, col, self.formats["header"])
            for j, value in enumerate(vals):
                # pandas numeric Series may coerce mapped None back to NaN.
                # Normalize at the final write boundary, after leaving pandas.
                value = cell_value(value)
                if isinstance(value, str) and len(value) > 32767:
                    raise ValueError(f"Excel cell exceeds 32,767 characters: {ws.name} {col}; preserve CSV and review field.")
                wrap = isinstance(value, str) and len(value) > width * 1.2 and (not data_sheet or col in {"asset_name", "site_name"})
                ws.write(start + j + 1, i, value, self.formats["wrap"] if wrap else fmt)
        ws.set_row(start, 36)
        for i, values in enumerate(frame.itertuples(index=False, name=None)):
            if not data_sheet:
                largest = max((math.ceil(len(str(cell_value(v) or "")) / max(12, self.column_widths[(ws.name, j)] * .92))
                               for j, v in enumerate(values)), default=1)
                ws.set_row(start + i + 1, min(160, max(20, largest * 15)))
            else:
                largest = max((math.ceil(len(str(cell_value(v) or "")) / max(12, self.column_widths[(ws.name, j)] * .92))
                               for j, (col, v) in enumerate(zip(frame.columns, values)) if col in {"asset_name", "site_name"}), default=1)
                ws.set_row(start + i + 1, max(20, min(90, largest * 15)))
        self.table_number += 1
        if len(frame):
            ws.add_table(start, 0, start + len(frame), len(frame.columns) - 1,
                         {"name": f"MAPC_Table_{self.table_number}", "style": "Table Style Medium 2",
                          "columns": [{"header": str(c), "header_format": self.formats["header"]} for c in frame.columns],
                          "autofilter": True, "banded_rows": True})
        else:
            ws.write(start + 1, 0, "No records in this population", self.formats["note"])
        self.specs.append({"sheet": ws.name, "start_row": start + 1, "row_count": len(frame), "column_count": len(frame.columns),
                           "columns": list(frame.columns)})
        return start + max(len(frame), 1) + 4

    def close(self):
        self.workbook.close()
        return verify_workbook(self.path, self.specs)


def verify_workbook(path, specs):
    """Read the saved OOXML file and verify table sizes/types and error cells."""
    wb = load_workbook(path, read_only=False, data_only=True)
    result = {"path": str(Path(path).name), "sheets": len(wb.sheetnames), "tables_checked": len(specs), "errors": []}
    for spec in specs:
        ws = wb[spec["sheet"]]
        header = [ws.cell(spec["start_row"], c + 1).value for c in range(spec["column_count"])]
        if header != spec["columns"]:
            result["errors"].append(f"Header mismatch: {ws.title}")
        for row in ws.iter_rows(min_row=spec["start_row"] + 1,
                                max_row=spec["start_row"] + spec["row_count"], max_col=spec["column_count"]):
            for col, cell in zip(spec["columns"], row):
                if cell.data_type == "e":
                    result["errors"].append(f"Excel error {ws.title}!{cell.coordinate}: {cell.value}")
                numeric_name = col in {"n", "frequency", "count", "n_assets", "n_profile_assets"} or col.endswith("_count") or "share" in col.split("_") or col.endswith("_mean")
                if numeric_name and cell.value is not None and not isinstance(cell.value, (int, float)):
                    result["errors"].append(f"Nonnumeric count/share {ws.title}!{cell.coordinate}")
    wb.close()
    if result["errors"]:
        raise AssertionError("Workbook verification failed: " + "; ".join(result["errors"][:8]))
    result["status"] = "passed"
    return result


def export_workbooks(assets, sites, tables, root, config, qc=None):
    root = Path(root)
    from .parse_attributes import build_attribute_dictionary, build_amenity_dictionary
    from .parse_activities import build_activity_dictionary
    from .documentation import build_data_dictionary
    data = root / "output/data"
    data.mkdir(parents=True, exist_ok=True)
    (root / "output/documentation").mkdir(parents=True, exist_ok=True)
    results = []
    for name, frame in [("assets_clean", assets), ("sites_summary", sites)]:
        csv_frame(frame).to_csv(data / f"{name}.csv", index=False, encoding="utf-8-sig")
        book = Book(data / f"{name}.xlsx")
        ws = book.sheet("Assets" if name == "assets_clean" else "Sites")
        leading = ["record_status", "asset_name", "site_name", "municipality", "subregion", "field_validated", "staff_reviewed",
                   "asset_count", "validated_asset_count", "attribute_count", "amenity_count", "activity_count",
                   "transportation_access_profile", "asset_id", "site_id"]
        order = [c for c in leading if c in frame] + [c for c in frame if c not in leading]
        book.table(ws, frame[order], data_sheet=True)
        ws.freeze_panes(1, min(3, len(frame.columns))); ws.repeat_rows(0)
        results.append(book.close())
    for name, frame in [("attribute_dictionary", build_attribute_dictionary(assets, config, root)),
                        ("amenity_dictionary", build_amenity_dictionary(assets, config, root)),
                        ("activity_dictionary", build_activity_dictionary(assets))]:
        csv_frame(frame).to_csv(data / f"{name}.csv", index=False, encoding="utf-8-sig")
    book = Book(root / "output/analysis/analysis_workbook.xlsx")
    overview = book.sheet("Overview", "MAPC recreation inventory analysis")
    overview.set_tab_color("#17324D")
    row = book.table(overview, tables["quality"].iloc[[3, 4, 5]], row=4, title="Analysis population")
    overview.write(row, 0, "Population: accepted, field-validated, unique assets. Site analysis uses only those members.", book.formats["note"])
    overview.write(row + 1, 0, "All results are descriptive. Rerun the Python pipeline after changing inputs; Excel is a saved analytical release.", book.formats["note"])
    row = book.table(overview, tables["findings"], row=row + 4, title="Thirteen research questions")
    overview.freeze_panes(4, 0)
    sheet_specs = [
        ("Asset-level analysis", [("asset_profiles", "Counts by transportation profile"), ("correlations", "Feature/activity rank relationships")]),
        ("Site-level analysis", [("site_profiles", "Site unions by transportation profile"), ("validated_sites", "Sites built from validated assets only")]),
        ("Transportation profiles", [("asset_profiles", "Asset profiles"), ("free_parking_transit", "Public transit and free entry/parking"), ("transport_combinations", "All transportation dimensions")]),
        ("Attributes and amenities", [("attributes", "All structured attributes/features"), ("amenities", "Classified physical amenity tags")]),
        ("Activities", [("activities", "Recorded activity vocabulary"), ("activity_profiles", "Activity share within profile")]),
        ("Accessibility", [("accessibility", "YES, NO and UNKNOWN denominators"), ("accessibility_cooccurrence", "Pairwise co-occurrence"), ("accessibility_richness", "Broader feature richness")]),
        ("Transit analysis", [("transit_groups", "Audited transit groups"), ("transit_comparison", "Structured source vs independent MBTA calculation")]),
        ("Bike and trail proximity", [("bike_transit", "Existing bike infrastructure and transit"), ("shared_use_groups", "Existing shared-use path proximity")]),
        ("Subregion analysis", [("subregions", "Counts by MAPC subregion"), ("core_comparison", "Inner Core and other subregions")]),
    ]
    for name, sections in sheet_specs:
        ws = book.sheet(name, name)
        row = 4
        for table_name, title in sections:
            note = "Validated assets only; each site has equal weight in site summaries." if table_name in {"site_profiles", "validated_sites"} else None
            row = book.table(ws, tables[table_name], row, title, note=note)
        ws.freeze_panes(6, 1)
    chart = book.sheet("Chart source tables", "Chart source tables and linked Excel charts")
    source = tables["asset_profiles"][["transportation_access_profile", "n", "attribute_count_mean", "amenity_count_mean", "activity_count_mean"]].copy()
    book.table(chart, source, 4, title="Profile means used in comparison figures")
    if len(source):
        native = book.workbook.add_chart({"type": "column"})
        for col, color in [(2, "#0072B2"), (4, "#E69F00")]:
            native.add_series({"name": [chart.name, 5, col], "categories": [chart.name, 6, 0, 5 + len(source), 0],
                               "values": [chart.name, 6, col, 5 + len(source), col], "fill": {"color": color}, "border": {"none": True}})
        native.set_title({"name": "Mean features and activities by profile", "name_font": {"size": 12, "name": "Arial"}})
        native.set_y_axis({"name": "Mean count per validated asset", "major_gridlines": {"visible": True, "line": {"color": "#E5E9EE"}}})
        native.set_x_axis({"name": "Audited transportation profile", "num_font": {"size": 9}})
        native.set_legend({"position": "bottom", "font": {"size": 9}})
        native.set_size({"width": 710, "height": 390})
        chart.insert_chart("G5", native)
    row = max(29, len(source) + 10)
    for key, title in [("chart_scatter", "Scatter-plot observations"), ("accessibility_cooccurrence", "Accessibility heatmap"),
                       ("bike_transit", "Bike/transit stacked bars"), ("subregions", "Subregion feature means"),
                       ("site_profiles", "Site union comparison")]:
        row = book.table(chart, tables[key], row, title)
    chart.freeze_panes(6, 1)
    qsheet = book.sheet("QC and data quality", "Data quality and analytical coverage")
    row = book.table(qsheet, tables["quality"], 4, title="Population reconciliation")
    qsheet.write(row, 0, "Detailed schema, coordinate, duplicate, GIS and provenance diagnostics are in output/reports/QC_report.html.", book.formats["note"])
    qsheet.write(row + 1, 0, "UNKNOWN is an evidence gap. Quarantined source records are retained in Assets clean and excluded from analysis.", book.formats["note"])
    methods = [
        ("Population", "Field-validated, accepted, unique assets. Quarantine and unvalidated records remain in cleaned data but do not enter primary analysis."),
        ("Statistical unit", "Asset summaries are descriptive. Multiple assets can belong to one site. Separate site analyses union only validated members; no p-values or causal claims."),
        ("Count measures", "attribute_count includes all structured features, policies and access tags. amenity_count is the configured physical amenity-tag subset. Neither counts individual pieces of equipment."),
        ("Missing evidence", "Access uses YES/NO/UNKNOWN. A missing tag alone is UNKNOWN. Known denominators include YES+NO; all denominators also include UNKNOWN."),
        ("Transit", "Near transit is <=0.5 mile to MBTA service-linked stop/station points using EPSG:26986 planar distance. GTFS failure leaves calculated states UNKNOWN. Compare recorded and calculated values separately."),
        ("Bike and trail proximity", "Nearest eligible existing/public line distance uses full geometry in EPSG:26986. Proximity does not establish an entrance, pedestrian/cycling route or accessibility."),
        ("Site aggregation", "Site activities/features are unions. Any member YES gives site YES, all NO gives NO, otherwise UNKNOWN. Transit and parking can be supported by different members."),
        ("Part-whole relation", "Physical-accessibility tags are also included in total feature count; the richness table provides the remaining feature count after removing the three focus tags."),
        ("Source hierarchy", "Current MAPC CSV and local official GIS ZIPs are authoritative. Prior audits are review-only; exact matches are re-evaluated. Cached official MBTA snapshot supports independent calculation."),
        ("Source traceability", "See source_file, source_sha256, source_row_number, source_line_start/end and source_record_json in Assets clean. Run manifest identifies exact inputs, config, code, transit snapshot and outputs."),
        ("Refresh", "Replace input/assets CSV and rerun python -m src.pipeline. Workbook values and charts are rebuilt from source rather than editable model formulas."),
    ]
    methods_sheet = book.sheet("Methodology notes", "Definitions, sources and method")
    book.table(methods_sheet, pd.DataFrame(methods, columns=["topic", "method"]), 4)
    methods_sheet.set_column(0, 0, 29); methods_sheet.set_column(1, 1, 110)
    results.append(book.close())
    dictionary = build_data_dictionary(assets, sites, config, root)
    dictionary.to_csv(root / "output/documentation/data_dictionary.csv", index=False, encoding="utf-8-sig")
    book = Book(root / "output/documentation/data_dictionary.xlsx")
    for entity, frame in dictionary.groupby("dataset", sort=False):
        ws = book.sheet({"assets_clean": "Asset fields", "sites_summary": "Site fields", "factcheck_audit": "Fact-check audit fields"}.get(entity, entity[:31]))
        book.table(ws, frame.drop(columns="dataset"), data_sheet=False)
        ws.freeze_panes(1, 1); ws.repeat_rows(0)
    results.append(book.close())
    report = root / "output/reports/workbook_validation.json"
    report.parent.mkdir(parents=True, exist_ok=True)
    report.write_text(json.dumps({"method": "openpyxl read-back of saved OOXML, headers, dimensions, numeric count/share types, Excel error cells",
                                  "native_excel_recalculation": "Not required for static Python-computed tables; native Excel application not automated.",
                                  "workbooks": results}, indent=2), encoding="utf-8")
    return results
